server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/anthares-service?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 5

logging:
  level:
    org.zalando.logbook: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG
    org.springframework: ERROR
    root: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level ${spring.application.name:-} %X{traceId:-}  %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"